### ISSUE TITLE
Attentes du client

### ISSUE THREAD

**Issue by Mordaina** [heptastique/SIE#33]

**Comment by Mordaina** [comment]
A valider par @lulucasono

**Comment by M4p4ch3** [comment]
Validation
- [x] Lucas
- [ ] Oussama
- [ ] Dorian
- [ ] Vincent
- [ ] Victor
- [x] Etienne

**Comment by M4p4ch3** [comment]
Validé

**Comment by lulucasono** [comment]
Validé
